### ISSUE TITLE
若干文字が見ずらい

### ISSUE THREAD

**Issue by atiqu50** [raoyama/etc#29]

**Comment by atiqu50** [comment]
![default](https://user-images.githubusercontent.com/8600012/52532236-f14f5b00-2d64-11e9-97da-684805fb1b7d.PNG)
あと、セレクトボックスがなんか化ける

**Comment by atiqu50** [comment]
文字色が白でセレクトボックス内の背景と同一だったのが問題

**Comment by raoyama** [comment]
mac版chromeだと普通に文字が黒で見えてたから気づかなかったわ
